import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Post from "../components/Post";
import PostType from "../types/PostType";

type HomeProps = {
  posts: PostType[];
};

const Home: NextPage<HomeProps> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {posts.map((post) => (
        <Post
          key={post.id}
          userId={post.userId}
          id={post.id}
          title={post.title}
          body={post.body}
        />
      ))}
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const posts: PostType[] = await res.json();

  return {
    props: {
      posts,
    },
  };
};

export default Home;
